#ifndef _SYSNR_H_
#define _SYSNR_H_

/*
 * This file contains the system call numbers.
 * 
 * Note: holes are not allowed.
 */

/* at least 8 syscall per cacheline */
#define _SYS_read                                0
#define _SYS_write                               1
#define _SYS_open                                2
#define _SYS_close                               3
#define _SYS_stat                                4
#define _SYS_fstat                               5
#define _SYS_lstat                               6
#define _SYS_poll                                7
#define _SYS_lseek                               8
#define _SYS_mmap                                9
#define _SYS_mprotect                           10
#define _SYS_munmap                             11
#define _SYS_brk                                12
#define _SYS_sigaction                       13
#define _SYS_sigprocmask                     14
#define _SYS_sigreturn                       15
#define _SYS_ioctl                              16
#define _SYS_pread                            17
#define _SYS_pwrite                           18
#define _SYS_readv                              19
#define _SYS_writev                             20
#define _SYS_access                             21
#define _SYS_pipe                               22
#define _SYS_select                             23
#define _SYS_sched_yield                        24
#define _SYS_mremap                             25
#define _SYS_msync                              26
#define _SYS_mincore                            27
#define _SYS_madvise                            28
#define _SYS_shmget                             29
#define _SYS_shmat                              30
#define _SYS_shmctl                             31
#define _SYS_dup                                32
#define _SYS_dup2                               33
#define _SYS_pause                              34
#define _SYS_nanosleep                          35
#define _SYS_getitimer                          36
#define _SYS_alarm                              37
#define _SYS_setitimer                          38
#define _SYS_getpid                             39
#define _SYS_sendfile                           40
#define _SYS_socket                             41
#define _SYS_connect                            42
#define _SYS_accept                             43
#define _SYS_sendto                             44
#define _SYS_recvfrom                           45
#define _SYS_sendmsg                            46
#define _SYS_recvmsg                            47
#define _SYS_shutdown                           48
#define _SYS_bind                               49
#define _SYS_listen                             50
#define _SYS_getsockname                        51
#define _SYS_getpeername                        52
#define _SYS_socketpair                         53
#define _SYS_setsockopt                         54
#define _SYS_getsockopt                         55
#define _SYS_clone                              56
#define _SYS_fork                               57
#define _SYS_vfork                              58
#define _SYS_execve                             59
#define _SYS_exit                               60
#define _SYS_wait4                              61
#define _SYS_kill                               62
#define _SYS_uname                              63
#define _SYS_semget                             64
#define _SYS_semop                              65
#define _SYS_semctl                             66
#define _SYS_shmdt                              67
#define _SYS_msgget                             68
#define _SYS_msgsnd                             69
#define _SYS_msgrcv                             70
#define _SYS_msgctl                             71
#define _SYS_fcntl                              72
#define _SYS_flock                              73
#define _SYS_fsync                              74
#define _SYS_fdatasync                          75
#define _SYS_truncate                           76
#define _SYS_ftruncate                          77
#define _SYS_getdents                           78
#define _SYS_getcwd                             79
#define _SYS_chdir                              80
#define _SYS_fchdir                             81
#define _SYS_rename                             82
#define _SYS_mkdir                              83
#define _SYS_rmdir                              84
#define _SYS_creat                              85
#define _SYS_link                               86
#define _SYS_unlink                             87
#define _SYS_symlink                            88
#define _SYS_readlink                           89
#define _SYS_chmod                              90
#define _SYS_fchmod                             91
#define _SYS_chown                              92
#define _SYS_fchown                             93
#define _SYS_lchown                             94
#define _SYS_umask                              95
#define _SYS_gettimeofday                       96
#define _SYS_getrlimit                          97
#define _SYS_getrusage                          98
#define _SYS_sysinfo                            99
#define _SYS_times                             100
#define _SYS_ptrace                            101
#define _SYS_getuid                            102
#define _SYS_syslog                            103
#define _SYS_getgid                            104
#define _SYS_setuid                            105
#define _SYS_setgid                            106
#define _SYS_geteuid                           107
#define _SYS_getegid                           108
#define _SYS_setpgid                           109
#define _SYS_getppid                           110
#define _SYS_getpgrp                           111
#define _SYS_setsid                            112
#define _SYS_setreuid                          113
#define _SYS_setregid                          114
#define _SYS_getgroups                         115
#define _SYS_setgroups                         116
#define _SYS_setresuid                         117
#define _SYS_getresuid                         118
#define _SYS_setresgid                         119
#define _SYS_getresgid                         120
#define _SYS_getpgid                           121
#define _SYS_setfsuid                          122
#define _SYS_setfsgid                          123
#define _SYS_getsid                            124
#define _SYS_capget                            125
#define _SYS_capset                            126
#define _SYS_rt_sigpending                     127
#define _SYS_rt_sigtimedwait                   128
#define _SYS_rt_sigqueueinfo                   129
#define _SYS_rt_sigsuspend                     130
#define _SYS_sigaltstack                       131
#define _SYS_utime                             132
#define _SYS_mknod                             133
/* Only needed for a.out */
#define _SYS_uselib                            134
#define _SYS_personality                       135
#define _SYS_ustat                             136
#define _SYS_statfs                            137
#define _SYS_fstatfs                           138
#define _SYS_sysfs                             139
#define _SYS_getpriority                       140
#define _SYS_setpriority                       141
#define _SYS_sched_setparam                    142
#define _SYS_sched_getparam                    143
#define _SYS_sched_setscheduler                144
#define _SYS_sched_getscheduler                145
#define _SYS_sched_get_priority_max            146
#define _SYS_sched_get_priority_min            147
#define _SYS_sched_rr_get_interval             148
#define _SYS_mlock                             149
#define _SYS_munlock                           150
#define _SYS_mlockall                          151
#define _SYS_munlockall                        152
#define _SYS_vhangup                           153
#define _SYS_modify_ldt                        154
#define _SYS_pivot_root                        155
#define _SYS__sysctl                           156
#define _SYS_prctl                             157
#define _SYS_arch_prctl                        158
#define _SYS_adjtimex                          159
#define _SYS_setrlimit                         160
#define _SYS_chroot                            161
#define _SYS_sync                              162
#define _SYS_acct                              163
#define _SYS_settimeofday                      164
#define _SYS_mount                             165
#define _SYS_umount2                           166
#define _SYS_swapon                            167
#define _SYS_swapoff                           168
#define _SYS_reboot                            169
#define _SYS_sethostname                       170
#define _SYS_setdomainname                     171
#define _SYS_iopl                              172
#define _SYS_ioperm                            173
#define _SYS_create_module                     174
#define _SYS_init_module                       175
#define _SYS_delete_module                     176
#define _SYS_get_kernel_syms                   177
#define _SYS_query_module                      178
#define _SYS_quotactl                          179
#define _SYS_nfsservctl                        180
#define _SYS_getpmsg                           181	/* reserved for LiS/STREAMS */
#define _SYS_putpmsg                           182	/* reserved for LiS/STREAMS */
#define _SYS_afs_syscall                       183	/* reserved for AFS */ 
#define _SYS_tuxcall      		184 /* reserved for tux */
#define _SYS_security			185
#define _SYS_gettid		186
#define _SYS_readahead		187
#define _SYS_setxattr		188
#define _SYS_lsetxattr		189
#define _SYS_fsetxattr		190
#define _SYS_getxattr		191
#define _SYS_lgetxattr		192
#define _SYS_fgetxattr		193
#define _SYS_listxattr		194
#define _SYS_llistxattr		195
#define _SYS_flistxattr		196
#define _SYS_removexattr	197
#define _SYS_lremovexattr	198
#define _SYS_fremovexattr	199
#define _SYS_tkill	200
#define _SYS_time      201
#define _SYS_futex     202
#define _SYS_sched_setaffinity    203
#define _SYS_sched_getaffinity     204
#define _SYS_set_thread_area	205
#define _SYS_io_setup	206
#define _SYS_io_destroy	207
#define _SYS_io_getevents	208
#define _SYS_io_submit	209
#define _SYS_io_cancel	210
#define _SYS_get_thread_area	211
#define _SYS_lookup_dcookie	212
#define _SYS_epoll_create	213
#define _SYS_epoll_ctl_old	214
#define _SYS_epoll_wait_old	215
#define _SYS_remap_file_pages	216
#define _SYS_getdents64	217
#define _SYS_set_tid_address	218
#define _SYS_restart_syscall	219
#define _SYS_semtimedop		220
#define _SYS_fadvise64		221
#define _SYS_timer_create		222
#define _SYS_timer_settime		223
#define _SYS_timer_gettime		224
#define _SYS_timer_getoverrun		225
#define _SYS_timer_delete	226
#define _SYS_clock_settime	227
#define _SYS_clock_gettime	228
#define _SYS_clock_getres	229
#define _SYS_clock_nanosleep	230
#define _SYS_exit_group		231
#define _SYS_epoll_wait		232
#define _SYS_epoll_ctl		233
#define _SYS_tgkill		234
#define _SYS_utimes		235
#define _SYS_vserver		236
#define _SYS_mbind 		237
#define _SYS_set_mempolicy 	238
#define _SYS_get_mempolicy 	239
#define _SYS_mq_open 		240
#define _SYS_mq_unlink 		241
#define _SYS_mq_timedsend 	242
#define _SYS_mq_timedreceive	243
#define _SYS_mq_notify 		244
#define _SYS_mq_getsetattr 	245
#define _SYS_kexec_load 	246
#define _SYS_waitid		247
#define _SYS_add_key		248
#define _SYS_request_key	249
#define _SYS_keyctl		250
#define _SYS_ioprio_set		251
#define _SYS_ioprio_get		252
#define _SYS_inotify_init	253
#define _SYS_inotify_add_watch	254
#define _SYS_inotify_rm_watch	255
#define _SYS_migrate_pages	256
#define _SYS_openat		257
#define _SYS_mkdirat		258
#define _SYS_mknodat		259
#define _SYS_fchownat		260
#define _SYS_futimesat		261
#define _SYS_newfstatat		262
#define _SYS_unlinkat		263
#define _SYS_renameat		264
#define _SYS_linkat		265
#define _SYS_symlinkat		266
#define _SYS_readlinkat		267
#define _SYS_fchmodat		268
#define _SYS_faccessat		269
#define _SYS_pselect6		270
#define _SYS_ppoll		271
#define _SYS_unshare		272
#define _SYS_set_robust_list	273
#define _SYS_get_robust_list	274
#define _SYS_splice		275
#define _SYS_tee		276
#define _SYS_sync_file_range	277
#define _SYS_vmsplice		278
#define _SYS_move_pages		279
#define _SYS_utimensat		280
#define _SYS_epoll_pwait	281
#define _SYS_signalfd		282
#define _SYS_timerfd_create	283
#define _SYS_eventfd		284
#define _SYS_fallocate		285
#define _SYS_timerfd_settime	286
#define _SYS_timerfd_gettime	287
#define _SYS_accept4		288
#define _SYS_signalfd4		289
#define _SYS_eventfd2		290
#define _SYS_epoll_create1	291
#define _SYS_dup3		292
#define _SYS_pipe2		293
#define _SYS_inotify_init1	294
#define _SYS_preadv		295
#define _SYS_pwritev		296
#define _SYS_rt_tgsigqueueinfo	297
#define _SYS_perf_event_open	298
#define _SYS_recvmmsg		299

#define _SYS_MAX_NR_  300

#endif /* _ASM_X86_64_UNISTD_H_ */
