all:
	gcc -g -O0 -o test test.c -rdynamic /nfs/cm/scratch1/tonyliu/grace/branches/DoubleTake/libdoubletake64.so
#	clang -g -O0 -o test test.c -rdynamic /nfs/cm/scratch1/tonyliu/grace/branches/DoubleTake/libdoubletake64.so
#	clang -m64 -g -fPIC -g -O0 -o test test.c -rdynamic /nfs/cm/scratch1/tonyliu/grace/branches/DoubleTake/libdoubletake64.so

clean:
	rm -f test
