all:
	g++ -g -O0 -o leak1 leak1.cpp -rdynamic /nfs/cm/scratch1/tonyliu/grace/branches/DoubleTake/DoubleTakeCharlie/DoubleTake/libdoubletake.so
#	g++ -g -O0 -o leak1 leak1.cpp -rdynamic /nfs/cm/scratch1/tonyliu/grace/branches/DoubleTake/DoubleTakeCharlie/DoubleTake/libdoubletake.so

clean:
	rm -f leak1
