#if !defined(DOUBLETAKE_REAL_H)
#define DOUBLETAKE_REAL_H

#include <dlfcn.h>

#include <dirent.h>
#include <fcntl.h>
#include <grp.h>
#include <malloc.h>
#include <mqueue.h>
#include <pthread.h>
#include <poll.h>
#include <sched.h>
#include <signal.h>
#include <stdlib.h>
#include <syslog.h>
#include <sys/epoll.h>
#include <sys/file.h>
#include <sys/fsuid.h>
#include <sys/inotify.h>
#include <sys/io.h>
#include <sys/ioctl.h>
#include <sys/ipc.h>
#include <sys/mman.h>
#include <sys/mount.h>
#include <sys/personality.h>
#include <sys/prctl.h>
#include <sys/ptrace.h>
#include <sys/reboot.h>
#include <sys/resource.h>
#include <sys/sem.h>
#include <sys/sendfile.h>
#include <sys/shm.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/statfs.h>
#include <sys/swap.h>
#include <sys/sysctl.h>
#include <sys/sysinfo.h>
#include <sys/time.h>
#include <sys/times.h>
#include <sys/timex.h>
#include <sys/types.h>
#include <sys/uio.h>
#include <sys/utsname.h>
#include <sys/vfs.h>
#include <sys/wait.h>
#include <sys/xattr.h>
#include <time.h>
#include <unistd.h>
#include <ustat.h>
#include <utime.h>

#define DECLARE_WRAPPER(name, handle) \
  typeof(::name) * Real::name;

#define DEFINE_WRAPPER(name, handle) \
  static typeof(::name) * name;

#define INIT_WRAPPER(name, handle) \
  name = (typeof(::name)*)dlsym(handle, #name); 

class Real {
private:
	
  static void* pthread_handle() {
    static void* _handle = dlopen("libpthread.so.0", RTLD_NOW | RTLD_GLOBAL | RTLD_NOLOAD);
    return _handle;
  }
  
public:
  // No libc wrappers
  //DEFINE_WRAPPER(getdents, RTLD_NEXT);
  //DEFINE_WRAPPER(modify_ldt, RTLD_NEXT);
  //DEFINE_WRAPPER(uselib, RTLD_NEXT);
  //DEFINE_WRAPPER(sysfs, RTLD_NEXT);
  //DEFINE_WRAPPER(gettid, RTLD_NEXT);
  //DEFINE_WRAPPER(tkill, RTLD_NEXT);
  //DEFINE_WRAPPER(set_thread_area, RTLD_NEXT);
  //DEFINE_WRAPPER(get_thread_area, RTLD_NEXT);
  //DEFINE_WRAPPER(io_setup, RTLD_NEXT);
  //DEFINE_WRAPPER(io_destroy, RTLD_NEXT);
  //DEFINE_WRAPPER(io_getevents, RTLD_NEXT);
  //DEFINE_WRAPPER(io_submit, RTLD_NEXT);
  //DEFINE_WRAPPER(io_cancel, RTLD_NEXT);
  //DEFINE_WRAPPER(lookup_dcookie, RTLD_NEXT);
  //DEFINE_WRAPPER(sys_tgkill, RTLD_NEXT);
  //DEFINE_WRAPPER(mq_getsetattr, RTLD_NEXT);
  //DEFINE_WRAPPER(ioprio_get, RTLD_NEXT);
  //DEFINE_WRAPPER(ioprio_set, RTLD_NEXT);
  //DEFINE_WRAPPER(get_robust_list, RTLD_NEXT);
  //DEFINE_WRAPPER(set_robust_list, RTLD_NEXT);
  //DEFINE_WRAPPER(pivot_root, RTLD_NEXT);
  //DEFINE_WRAPPER(arch_prctl, RTLD_NEXT);
  //DEFINE_WRAPPER(futex, RTLD_NEXT);
  //DEFINE_WRAPPER(set_tid_address, RTLD_NEXT);
  //DEFINE_WRAPPER(restart_syscall, RTLD_NEXT);
  //DEFINE_WRAPPER(exit_group, RTLD_NEXT);
  //DEFINE_WRAPPER(add_key, RTLD_NEXT);
  //DEFINE_WRAPPER(request_key, RTLD_NEXT);
  //DEFINE_WRAPPER(keyctl, RTLD_NEXT);
  //DEFINE_WRAPPER(move_pages, RTLD_NEXT);
//  DEFINE_WRAPPER(kexec_load, RTLD_NEXT);
  
  DEFINE_WRAPPER(accept, RTLD_NEXT);
  DEFINE_WRAPPER(access, RTLD_NEXT);
  DEFINE_WRAPPER(acct, RTLD_NEXT);
  DEFINE_WRAPPER(adjtimex, RTLD_NEXT);
  DEFINE_WRAPPER(alarm, RTLD_NEXT);
  DEFINE_WRAPPER(bind, RTLD_NEXT);
  DEFINE_WRAPPER(brk, RTLD_NEXT);
  DEFINE_WRAPPER(chdir, RTLD_NEXT);
  DEFINE_WRAPPER(chmod, RTLD_NEXT);
  DEFINE_WRAPPER(chown, RTLD_NEXT);
  DEFINE_WRAPPER(chroot, RTLD_NEXT);
  DEFINE_WRAPPER(clock_getres, RTLD_NEXT);
  DEFINE_WRAPPER(clock_gettime, RTLD_NEXT);
  DEFINE_WRAPPER(clock_nanosleep, RTLD_NEXT);
  DEFINE_WRAPPER(clock_settime, RTLD_NEXT);
  DEFINE_WRAPPER(clone, RTLD_NEXT);
  DEFINE_WRAPPER(close, RTLD_NEXT);
  DEFINE_WRAPPER(closedir, RTLD_NEXT);
  DEFINE_WRAPPER(connect, RTLD_NEXT);
  DEFINE_WRAPPER(creat, RTLD_NEXT);
  DEFINE_WRAPPER(dup, RTLD_NEXT);
  DEFINE_WRAPPER(dup2, RTLD_NEXT);
  DEFINE_WRAPPER(epoll_create, RTLD_NEXT);
  DEFINE_WRAPPER(epoll_ctl, RTLD_NEXT);
  DEFINE_WRAPPER(epoll_wait, RTLD_NEXT);
  DEFINE_WRAPPER(execve, RTLD_NEXT);
  DEFINE_WRAPPER(exit, RTLD_NEXT);
  DEFINE_WRAPPER(faccessat, RTLD_NEXT);
  DEFINE_WRAPPER(fchdir, RTLD_NEXT);
  DEFINE_WRAPPER(fchmod, RTLD_NEXT);
  DEFINE_WRAPPER(fchmodat, RTLD_NEXT);
  DEFINE_WRAPPER(fchown, RTLD_NEXT);
  DEFINE_WRAPPER(fchownat, RTLD_NEXT);
  DEFINE_WRAPPER(fclose, RTLD_NEXT);
  DEFINE_WRAPPER(fcntl, RTLD_NEXT);
  DEFINE_WRAPPER(fdatasync, RTLD_NEXT);
  DEFINE_WRAPPER(fgetxattr, RTLD_NEXT);
  DEFINE_WRAPPER(flistxattr, RTLD_NEXT);
  DEFINE_WRAPPER(flock, RTLD_NEXT);
  DEFINE_WRAPPER(printf, RTLD_NEXT);
  DEFINE_WRAPPER(puts, RTLD_NEXT);
  DEFINE_WRAPPER(fopen, RTLD_NEXT);
  DEFINE_WRAPPER(fopen64, RTLD_NEXT);
  DEFINE_WRAPPER(fork, RTLD_NEXT);
  DEFINE_WRAPPER(fread, RTLD_NEXT);
  DEFINE_WRAPPER(free, RTLD_NEXT);
  DEFINE_WRAPPER(fremovexattr, RTLD_NEXT);
  DEFINE_WRAPPER(fsetxattr, RTLD_NEXT);
  DEFINE_WRAPPER(fstat, RTLD_NEXT);
  DEFINE_WRAPPER(fstatfs, RTLD_NEXT);
  DEFINE_WRAPPER(fsync, RTLD_NEXT);
  DEFINE_WRAPPER(ftruncate, RTLD_NEXT);
  DEFINE_WRAPPER(futimesat, RTLD_NEXT);
  DEFINE_WRAPPER(fwrite, RTLD_NEXT);
  DEFINE_WRAPPER(getcwd, RTLD_NEXT);
  DEFINE_WRAPPER(getegid, RTLD_NEXT);
  DEFINE_WRAPPER(geteuid, RTLD_NEXT);
  DEFINE_WRAPPER(getgid, RTLD_NEXT);
  DEFINE_WRAPPER(getgroups, RTLD_NEXT);
  DEFINE_WRAPPER(getitimer, RTLD_NEXT);
  DEFINE_WRAPPER(getpeername, RTLD_NEXT);
  DEFINE_WRAPPER(getpgid, RTLD_NEXT);
  DEFINE_WRAPPER(getpgrp, RTLD_NEXT);
  DEFINE_WRAPPER(getpid, RTLD_NEXT);
  DEFINE_WRAPPER(getppid, RTLD_NEXT);
  DEFINE_WRAPPER(getpriority, RTLD_NEXT);
  DEFINE_WRAPPER(getresgid, RTLD_NEXT);
  DEFINE_WRAPPER(getresuid, RTLD_NEXT);
  DEFINE_WRAPPER(getrlimit, RTLD_NEXT);
  DEFINE_WRAPPER(getrusage, RTLD_NEXT);
  DEFINE_WRAPPER(getsid, RTLD_NEXT);
  DEFINE_WRAPPER(getsockname, RTLD_NEXT);
  DEFINE_WRAPPER(getsockopt, RTLD_NEXT);
  DEFINE_WRAPPER(gettimeofday, RTLD_NEXT);
  DEFINE_WRAPPER(getuid, RTLD_NEXT);
  DEFINE_WRAPPER(getxattr, RTLD_NEXT);
  DEFINE_WRAPPER(inotify_add_watch, RTLD_NEXT);
  DEFINE_WRAPPER(inotify_init, RTLD_NEXT);
  DEFINE_WRAPPER(inotify_rm_watch, RTLD_NEXT);
  DEFINE_WRAPPER(ioctl, RTLD_NEXT);
  DEFINE_WRAPPER(ioperm, RTLD_NEXT);
  DEFINE_WRAPPER(iopl, RTLD_NEXT);
  DEFINE_WRAPPER(kill, RTLD_NEXT);
  DEFINE_WRAPPER(lchown, RTLD_NEXT);
  DEFINE_WRAPPER(lgetxattr, RTLD_NEXT);
  DEFINE_WRAPPER(link, RTLD_NEXT);
  DEFINE_WRAPPER(linkat, RTLD_NEXT);
  DEFINE_WRAPPER(listen, RTLD_NEXT);
  DEFINE_WRAPPER(listxattr, RTLD_NEXT);
  DEFINE_WRAPPER(llistxattr, RTLD_NEXT);
  DEFINE_WRAPPER(lremovexattr, RTLD_NEXT);
  DEFINE_WRAPPER(lseek, RTLD_NEXT);
  DEFINE_WRAPPER(lsetxattr, RTLD_NEXT);
  DEFINE_WRAPPER(lstat, RTLD_NEXT);
  DEFINE_WRAPPER(madvise, RTLD_NEXT);
  DEFINE_WRAPPER(malloc, RTLD_NEXT);
  DEFINE_WRAPPER(malloc_usable_size, RTLD_NEXT);
  DEFINE_WRAPPER(memalign, RTLD_NEXT);
  DEFINE_WRAPPER(mincore, RTLD_NEXT);
  DEFINE_WRAPPER(mkdir, RTLD_NEXT);
  DEFINE_WRAPPER(mkdirat, RTLD_NEXT);
  DEFINE_WRAPPER(mknod, RTLD_NEXT);
  DEFINE_WRAPPER(mknodat, RTLD_NEXT);
  DEFINE_WRAPPER(mlock, RTLD_NEXT);
  DEFINE_WRAPPER(mlockall, RTLD_NEXT);
  DEFINE_WRAPPER(mmap, RTLD_NEXT);
  DEFINE_WRAPPER(mount, RTLD_NEXT);
  DEFINE_WRAPPER(mprotect, RTLD_NEXT);
  DEFINE_WRAPPER(mq_notify, RTLD_NEXT);
  DEFINE_WRAPPER(mq_open, RTLD_NEXT);
  DEFINE_WRAPPER(mq_timedreceive, RTLD_NEXT);
  DEFINE_WRAPPER(mq_timedsend, RTLD_NEXT);
  DEFINE_WRAPPER(mq_unlink, RTLD_NEXT);
  DEFINE_WRAPPER(mremap, RTLD_NEXT);
  DEFINE_WRAPPER(msync, RTLD_NEXT);
  DEFINE_WRAPPER(munlock, RTLD_NEXT);
  DEFINE_WRAPPER(munlockall, RTLD_NEXT);
  DEFINE_WRAPPER(munmap, RTLD_NEXT);
  DEFINE_WRAPPER(nanosleep, RTLD_NEXT);
  DEFINE_WRAPPER(open, RTLD_NEXT);
  DEFINE_WRAPPER(openat, RTLD_NEXT);
  DEFINE_WRAPPER(opendir, RTLD_NEXT);
  DEFINE_WRAPPER(pause, RTLD_NEXT);
  DEFINE_WRAPPER(personality, RTLD_NEXT);
  DEFINE_WRAPPER(pipe, RTLD_NEXT);
  DEFINE_WRAPPER(poll, RTLD_NEXT);
  DEFINE_WRAPPER(posix_fadvise64, RTLD_NEXT);
  DEFINE_WRAPPER(ppoll, RTLD_NEXT);
  DEFINE_WRAPPER(prctl, RTLD_NEXT);
  DEFINE_WRAPPER(pread, RTLD_NEXT);
  DEFINE_WRAPPER(pselect, RTLD_NEXT);
  
  DEFINE_WRAPPER(pthread_barrier_destroy, pthread_handle());
  DEFINE_WRAPPER(pthread_barrier_init, pthread_handle());
  DEFINE_WRAPPER(pthread_barrier_wait, pthread_handle());
  DEFINE_WRAPPER(pthread_cancel, pthread_handle());
  DEFINE_WRAPPER(pthread_condattr_init, pthread_handle());
  DEFINE_WRAPPER(pthread_cond_broadcast, pthread_handle());
  DEFINE_WRAPPER(pthread_cond_destroy, pthread_handle());
  DEFINE_WRAPPER(pthread_cond_init, pthread_handle());
  DEFINE_WRAPPER(pthread_cond_signal, pthread_handle());
  DEFINE_WRAPPER(pthread_cond_wait, pthread_handle());
  DEFINE_WRAPPER(pthread_create, pthread_handle());
  DEFINE_WRAPPER(pthread_detach, pthread_handle());
  DEFINE_WRAPPER(pthread_exit, pthread_handle());
  DEFINE_WRAPPER(pthread_join, pthread_handle());
  DEFINE_WRAPPER(pthread_kill, pthread_handle());
  DEFINE_WRAPPER(pthread_mutexattr_init, pthread_handle());
  DEFINE_WRAPPER(pthread_mutex_destroy, pthread_handle());
  DEFINE_WRAPPER(pthread_mutex_init, pthread_handle());
  DEFINE_WRAPPER(pthread_mutex_lock, pthread_handle());
  DEFINE_WRAPPER(pthread_mutex_trylock, pthread_handle());
  DEFINE_WRAPPER(pthread_mutex_unlock, pthread_handle());
  DEFINE_WRAPPER(pthread_self, pthread_handle());
  
  DEFINE_WRAPPER(ptrace, RTLD_NEXT);
  DEFINE_WRAPPER(pwrite, RTLD_NEXT);
  DEFINE_WRAPPER(read, RTLD_NEXT);
  DEFINE_WRAPPER(readahead, RTLD_NEXT);
  DEFINE_WRAPPER(readlink, RTLD_NEXT);
  DEFINE_WRAPPER(readlinkat, RTLD_NEXT);
  DEFINE_WRAPPER(readv, RTLD_NEXT);
  DEFINE_WRAPPER(realloc, RTLD_NEXT);
  DEFINE_WRAPPER(reboot, RTLD_NEXT);
  DEFINE_WRAPPER(recvfrom, RTLD_NEXT);
  DEFINE_WRAPPER(recvmsg, RTLD_NEXT);
  DEFINE_WRAPPER(remap_file_pages, RTLD_NEXT);
  DEFINE_WRAPPER(removexattr, RTLD_NEXT);
  DEFINE_WRAPPER(rename, RTLD_NEXT);
  DEFINE_WRAPPER(renameat, RTLD_NEXT);
  DEFINE_WRAPPER(rmdir, RTLD_NEXT);
  DEFINE_WRAPPER(sched_getaffinity, RTLD_NEXT);
  DEFINE_WRAPPER(sched_getparam, RTLD_NEXT);
  DEFINE_WRAPPER(sched_getscheduler, RTLD_NEXT);
  DEFINE_WRAPPER(sched_get_priority_max, RTLD_NEXT);
  DEFINE_WRAPPER(sched_get_priority_min, RTLD_NEXT);
  DEFINE_WRAPPER(sched_rr_get_interval, RTLD_NEXT);
  DEFINE_WRAPPER(sched_setaffinity, RTLD_NEXT);
  DEFINE_WRAPPER(sched_setparam, RTLD_NEXT);
  DEFINE_WRAPPER(sched_setscheduler, RTLD_NEXT);
  DEFINE_WRAPPER(sched_yield, RTLD_NEXT);
  DEFINE_WRAPPER(select, RTLD_NEXT);
  DEFINE_WRAPPER(semctl, RTLD_NEXT);
  DEFINE_WRAPPER(semget, RTLD_NEXT);
  DEFINE_WRAPPER(semop, RTLD_NEXT);
  DEFINE_WRAPPER(semtimedop, RTLD_NEXT);
  DEFINE_WRAPPER(sendfile, RTLD_NEXT);
  DEFINE_WRAPPER(sendmsg, RTLD_NEXT);
  DEFINE_WRAPPER(sendto, RTLD_NEXT);
  DEFINE_WRAPPER(setdomainname, RTLD_NEXT);
  DEFINE_WRAPPER(setfsgid, RTLD_NEXT);
  DEFINE_WRAPPER(setfsuid, RTLD_NEXT);
  DEFINE_WRAPPER(setgid, RTLD_NEXT);
  DEFINE_WRAPPER(setgroups, RTLD_NEXT);
  DEFINE_WRAPPER(sethostname, RTLD_NEXT);
  DEFINE_WRAPPER(setitimer, RTLD_NEXT);
  DEFINE_WRAPPER(setpgid, RTLD_NEXT);
  DEFINE_WRAPPER(setpriority, RTLD_NEXT);
  DEFINE_WRAPPER(setregid, RTLD_NEXT);
  DEFINE_WRAPPER(setresgid, RTLD_NEXT);
  DEFINE_WRAPPER(setresuid, RTLD_NEXT);
  DEFINE_WRAPPER(setreuid, RTLD_NEXT);
  DEFINE_WRAPPER(setrlimit, RTLD_NEXT);
  DEFINE_WRAPPER(setsid, RTLD_NEXT);
  DEFINE_WRAPPER(setsockopt, RTLD_NEXT);
  DEFINE_WRAPPER(settimeofday, RTLD_NEXT);
  DEFINE_WRAPPER(setuid, RTLD_NEXT);
  DEFINE_WRAPPER(setxattr, RTLD_NEXT);
  DEFINE_WRAPPER(shmat, RTLD_NEXT);
  DEFINE_WRAPPER(shmctl, RTLD_NEXT);
  DEFINE_WRAPPER(shmget, RTLD_NEXT);
  DEFINE_WRAPPER(shutdown, RTLD_NEXT);
  DEFINE_WRAPPER(sigaction, RTLD_NEXT);
  DEFINE_WRAPPER(sigaltstack, RTLD_NEXT);
  DEFINE_WRAPPER(sigpending, RTLD_NEXT);
  DEFINE_WRAPPER(sigprocmask, RTLD_NEXT);
  DEFINE_WRAPPER(sigreturn, RTLD_NEXT);
  DEFINE_WRAPPER(sigsuspend, RTLD_NEXT);
  DEFINE_WRAPPER(sigtimedwait, RTLD_NEXT);
  DEFINE_WRAPPER(sigwait, RTLD_NEXT);
  DEFINE_WRAPPER(socket, RTLD_NEXT);
  DEFINE_WRAPPER(socketpair, RTLD_NEXT);
  DEFINE_WRAPPER(splice, RTLD_NEXT);
  DEFINE_WRAPPER(stat, RTLD_NEXT);
  DEFINE_WRAPPER(statfs, RTLD_NEXT);
  DEFINE_WRAPPER(swapoff, RTLD_NEXT);
  DEFINE_WRAPPER(swapon, RTLD_NEXT);
  DEFINE_WRAPPER(symlink, RTLD_NEXT);
  DEFINE_WRAPPER(symlinkat, RTLD_NEXT);
  DEFINE_WRAPPER(sync, RTLD_NEXT);
  DEFINE_WRAPPER(sync_file_range, RTLD_NEXT);
  DEFINE_WRAPPER(sysctl, RTLD_NEXT);
  DEFINE_WRAPPER(sysinfo, RTLD_NEXT);
  DEFINE_WRAPPER(vsyslog, RTLD_NEXT);
  DEFINE_WRAPPER(tee, RTLD_NEXT);
  DEFINE_WRAPPER(time, RTLD_NEXT);
  DEFINE_WRAPPER(timer_create, RTLD_NEXT);
  DEFINE_WRAPPER(timer_delete, RTLD_NEXT);
  DEFINE_WRAPPER(timer_getoverrun, RTLD_NEXT);
  DEFINE_WRAPPER(timer_gettime, RTLD_NEXT);
  DEFINE_WRAPPER(timer_settime, RTLD_NEXT);
  DEFINE_WRAPPER(times, RTLD_NEXT);
  DEFINE_WRAPPER(truncate, RTLD_NEXT);
  DEFINE_WRAPPER(umask, RTLD_NEXT);
  DEFINE_WRAPPER(umount2, RTLD_NEXT);
  DEFINE_WRAPPER(uname, RTLD_NEXT);
  DEFINE_WRAPPER(unlink, RTLD_NEXT);
  DEFINE_WRAPPER(unlinkat, RTLD_NEXT);
  DEFINE_WRAPPER(unshare, RTLD_NEXT);
  DEFINE_WRAPPER(ustat, RTLD_NEXT);
  DEFINE_WRAPPER(utime, RTLD_NEXT);
  DEFINE_WRAPPER(utimes, RTLD_NEXT);
  DEFINE_WRAPPER(vfork, RTLD_NEXT);
  DEFINE_WRAPPER(vhangup, RTLD_NEXT);
  DEFINE_WRAPPER(vmsplice, RTLD_NEXT);
  DEFINE_WRAPPER(wait4, RTLD_NEXT);
  DEFINE_WRAPPER(waitid, RTLD_NEXT);
  DEFINE_WRAPPER(write, RTLD_NEXT);
  DEFINE_WRAPPER(writev, RTLD_NEXT);
 
	static void initializer(void) { 
	// No libc wrappers
  //INIT_WRAPPER(getdents, RTLD_NEXT);
  //INIT_WRAPPER(modify_ldt, RTLD_NEXT);
  //INIT_WRAPPER(uselib, RTLD_NEXT);
  //INIT_WRAPPER(sysfs, RTLD_NEXT);
  //INIT_WRAPPER(gettid, RTLD_NEXT);
  //INIT_WRAPPER(tkill, RTLD_NEXT);
  //INIT_WRAPPER(set_thread_area, RTLD_NEXT);
  //INIT_WRAPPER(get_thread_area, RTLD_NEXT);
  //INIT_WRAPPER(io_setup, RTLD_NEXT);
  //INIT_WRAPPER(io_destroy, RTLD_NEXT);
  //INIT_WRAPPER(io_getevents, RTLD_NEXT);
  //INIT_WRAPPER(io_submit, RTLD_NEXT);
  //INIT_WRAPPER(io_cancel, RTLD_NEXT);
  //INIT_WRAPPER(lookup_dcookie, RTLD_NEXT);
  //INIT_WRAPPER(sys_tgkill, RTLD_NEXT);
  //INIT_WRAPPER(mq_getsetattr, RTLD_NEXT);
  //INIT_WRAPPER(ioprio_get, RTLD_NEXT);
  //INIT_WRAPPER(ioprio_set, RTLD_NEXT);
  //INIT_WRAPPER(get_robust_list, RTLD_NEXT);
  //INIT_WRAPPER(set_robust_list, RTLD_NEXT);
  //INIT_WRAPPER(pivot_root, RTLD_NEXT);
  //INIT_WRAPPER(arch_prctl, RTLD_NEXT);
  //INIT_WRAPPER(futex, RTLD_NEXT);
  //INIT_WRAPPER(set_tid_address, RTLD_NEXT);
  //INIT_WRAPPER(restart_syscall, RTLD_NEXT);
  //INIT_WRAPPER(exit_group, RTLD_NEXT);
  //INIT_WRAPPER(add_key, RTLD_NEXT);
  //INIT_WRAPPER(request_key, RTLD_NEXT);
  //INIT_WRAPPER(keyctl, RTLD_NEXT);
  //INIT_WRAPPER(move_pages, RTLD_NEXT);
//  INIT_WRAPPER(kexec_load, RTLD_NEXT);
  
  INIT_WRAPPER(accept, RTLD_NEXT);
  INIT_WRAPPER(access, RTLD_NEXT);
  INIT_WRAPPER(acct, RTLD_NEXT);
  INIT_WRAPPER(adjtimex, RTLD_NEXT);
  INIT_WRAPPER(alarm, RTLD_NEXT);
  INIT_WRAPPER(bind, RTLD_NEXT);
  INIT_WRAPPER(brk, RTLD_NEXT);
  INIT_WRAPPER(chdir, RTLD_NEXT);
  INIT_WRAPPER(chmod, RTLD_NEXT);
  INIT_WRAPPER(chown, RTLD_NEXT);
  INIT_WRAPPER(chroot, RTLD_NEXT);
  INIT_WRAPPER(clock_getres, RTLD_NEXT);
  INIT_WRAPPER(clock_gettime, RTLD_NEXT);
  INIT_WRAPPER(clock_nanosleep, RTLD_NEXT);
  INIT_WRAPPER(clock_settime, RTLD_NEXT);
  INIT_WRAPPER(clone, RTLD_NEXT);
  INIT_WRAPPER(close, RTLD_NEXT);
  INIT_WRAPPER(closedir, RTLD_NEXT);
  INIT_WRAPPER(connect, RTLD_NEXT);
  INIT_WRAPPER(creat, RTLD_NEXT);
  INIT_WRAPPER(dup, RTLD_NEXT);
  INIT_WRAPPER(dup2, RTLD_NEXT);
  INIT_WRAPPER(epoll_create, RTLD_NEXT);
  INIT_WRAPPER(epoll_ctl, RTLD_NEXT);
  INIT_WRAPPER(epoll_wait, RTLD_NEXT);
  INIT_WRAPPER(execve, RTLD_NEXT);
  INIT_WRAPPER(exit, RTLD_NEXT);
  INIT_WRAPPER(faccessat, RTLD_NEXT);
  INIT_WRAPPER(fchdir, RTLD_NEXT);
  INIT_WRAPPER(fchmod, RTLD_NEXT);
  INIT_WRAPPER(fchmodat, RTLD_NEXT);
  INIT_WRAPPER(fchown, RTLD_NEXT);
  INIT_WRAPPER(fchownat, RTLD_NEXT);
  INIT_WRAPPER(fclose, RTLD_NEXT);
  INIT_WRAPPER(fcntl, RTLD_NEXT);
  INIT_WRAPPER(fdatasync, RTLD_NEXT);
  INIT_WRAPPER(fgetxattr, RTLD_NEXT);
  INIT_WRAPPER(flistxattr, RTLD_NEXT);
  INIT_WRAPPER(flock, RTLD_NEXT);
  INIT_WRAPPER(printf, RTLD_NEXT);
  INIT_WRAPPER(puts, RTLD_NEXT);
  INIT_WRAPPER(fopen, RTLD_NEXT);
  INIT_WRAPPER(fopen64, RTLD_NEXT);
  INIT_WRAPPER(fork, RTLD_NEXT);
  INIT_WRAPPER(fread, RTLD_NEXT);
  INIT_WRAPPER(free, RTLD_NEXT);
  INIT_WRAPPER(fremovexattr, RTLD_NEXT);
  INIT_WRAPPER(fsetxattr, RTLD_NEXT);
  INIT_WRAPPER(fstat, RTLD_NEXT);
  INIT_WRAPPER(fstatfs, RTLD_NEXT);
  INIT_WRAPPER(fsync, RTLD_NEXT);
  INIT_WRAPPER(ftruncate, RTLD_NEXT);
  INIT_WRAPPER(futimesat, RTLD_NEXT);
  INIT_WRAPPER(fwrite, RTLD_NEXT);
  INIT_WRAPPER(getcwd, RTLD_NEXT);
  INIT_WRAPPER(getegid, RTLD_NEXT);
  INIT_WRAPPER(geteuid, RTLD_NEXT);
  INIT_WRAPPER(getgid, RTLD_NEXT);
  INIT_WRAPPER(getgroups, RTLD_NEXT);
  INIT_WRAPPER(getitimer, RTLD_NEXT);
  INIT_WRAPPER(getpeername, RTLD_NEXT);
  INIT_WRAPPER(getpgid, RTLD_NEXT);
  INIT_WRAPPER(getpgrp, RTLD_NEXT);
  INIT_WRAPPER(getpid, RTLD_NEXT);
  INIT_WRAPPER(getppid, RTLD_NEXT);
  INIT_WRAPPER(getpriority, RTLD_NEXT);
  INIT_WRAPPER(getresgid, RTLD_NEXT);
  INIT_WRAPPER(getresuid, RTLD_NEXT);
  INIT_WRAPPER(getrlimit, RTLD_NEXT);
  INIT_WRAPPER(getrusage, RTLD_NEXT);
  INIT_WRAPPER(getsid, RTLD_NEXT);
  INIT_WRAPPER(getsockname, RTLD_NEXT);
  INIT_WRAPPER(getsockopt, RTLD_NEXT);
  INIT_WRAPPER(gettimeofday, RTLD_NEXT);
  INIT_WRAPPER(getuid, RTLD_NEXT);
  INIT_WRAPPER(getxattr, RTLD_NEXT);
  INIT_WRAPPER(inotify_add_watch, RTLD_NEXT);
  INIT_WRAPPER(inotify_init, RTLD_NEXT);
  INIT_WRAPPER(inotify_rm_watch, RTLD_NEXT);
  INIT_WRAPPER(ioctl, RTLD_NEXT);
  INIT_WRAPPER(ioperm, RTLD_NEXT);
  INIT_WRAPPER(iopl, RTLD_NEXT);
  INIT_WRAPPER(kill, RTLD_NEXT);
  INIT_WRAPPER(lchown, RTLD_NEXT);
  INIT_WRAPPER(lgetxattr, RTLD_NEXT);
  INIT_WRAPPER(link, RTLD_NEXT);
  INIT_WRAPPER(linkat, RTLD_NEXT);
  INIT_WRAPPER(listen, RTLD_NEXT);
  INIT_WRAPPER(listxattr, RTLD_NEXT);
  INIT_WRAPPER(llistxattr, RTLD_NEXT);
  INIT_WRAPPER(lremovexattr, RTLD_NEXT);
  INIT_WRAPPER(lseek, RTLD_NEXT);
  INIT_WRAPPER(lsetxattr, RTLD_NEXT);
  INIT_WRAPPER(lstat, RTLD_NEXT);
  INIT_WRAPPER(madvise, RTLD_NEXT);
  INIT_WRAPPER(malloc, RTLD_NEXT);
  INIT_WRAPPER(malloc_usable_size, RTLD_NEXT);
  INIT_WRAPPER(memalign, RTLD_NEXT);
  INIT_WRAPPER(mincore, RTLD_NEXT);
  INIT_WRAPPER(mkdir, RTLD_NEXT);
  INIT_WRAPPER(mkdirat, RTLD_NEXT);
  INIT_WRAPPER(mknod, RTLD_NEXT);
  INIT_WRAPPER(mknodat, RTLD_NEXT);
  INIT_WRAPPER(mlock, RTLD_NEXT);
  INIT_WRAPPER(mlockall, RTLD_NEXT);
  INIT_WRAPPER(mmap, RTLD_NEXT);
  INIT_WRAPPER(mount, RTLD_NEXT);
  INIT_WRAPPER(mprotect, RTLD_NEXT);
  INIT_WRAPPER(mq_notify, RTLD_NEXT);
  INIT_WRAPPER(mq_open, RTLD_NEXT);
  INIT_WRAPPER(mq_timedreceive, RTLD_NEXT);
  INIT_WRAPPER(mq_timedsend, RTLD_NEXT);
  INIT_WRAPPER(mq_unlink, RTLD_NEXT);
  INIT_WRAPPER(mremap, RTLD_NEXT);
  INIT_WRAPPER(msync, RTLD_NEXT);
  INIT_WRAPPER(munlock, RTLD_NEXT);
  INIT_WRAPPER(munlockall, RTLD_NEXT);
  INIT_WRAPPER(munmap, RTLD_NEXT);
  INIT_WRAPPER(nanosleep, RTLD_NEXT);
  INIT_WRAPPER(open, RTLD_NEXT);
  INIT_WRAPPER(openat, RTLD_NEXT);
  INIT_WRAPPER(opendir, RTLD_NEXT);
  INIT_WRAPPER(pause, RTLD_NEXT);
  INIT_WRAPPER(personality, RTLD_NEXT);
  INIT_WRAPPER(pipe, RTLD_NEXT);
  INIT_WRAPPER(poll, RTLD_NEXT);
  INIT_WRAPPER(posix_fadvise64, RTLD_NEXT);
  INIT_WRAPPER(ppoll, RTLD_NEXT);
  INIT_WRAPPER(prctl, RTLD_NEXT);
  INIT_WRAPPER(pread, RTLD_NEXT);
  INIT_WRAPPER(pselect, RTLD_NEXT);
  
  INIT_WRAPPER(pthread_barrier_destroy, pthread_handle());
  INIT_WRAPPER(pthread_barrier_init, pthread_handle());
  INIT_WRAPPER(pthread_barrier_wait, pthread_handle());
  INIT_WRAPPER(pthread_cancel, pthread_handle());
  INIT_WRAPPER(pthread_condattr_init, pthread_handle());
  INIT_WRAPPER(pthread_cond_broadcast, pthread_handle());
  INIT_WRAPPER(pthread_cond_destroy, pthread_handle());
  INIT_WRAPPER(pthread_cond_init, pthread_handle());
  INIT_WRAPPER(pthread_cond_signal, pthread_handle());
  INIT_WRAPPER(pthread_cond_wait, pthread_handle());
  INIT_WRAPPER(pthread_create, pthread_handle());
  INIT_WRAPPER(pthread_detach, pthread_handle());
  INIT_WRAPPER(pthread_exit, pthread_handle());
  INIT_WRAPPER(pthread_join, pthread_handle());
  INIT_WRAPPER(pthread_kill, pthread_handle());
  INIT_WRAPPER(pthread_mutexattr_init, pthread_handle());
  INIT_WRAPPER(pthread_mutex_destroy, pthread_handle());
  INIT_WRAPPER(pthread_mutex_init, pthread_handle());
  INIT_WRAPPER(pthread_mutex_lock, pthread_handle());
  INIT_WRAPPER(pthread_mutex_trylock, pthread_handle());
  INIT_WRAPPER(pthread_mutex_unlock, pthread_handle());
  INIT_WRAPPER(pthread_self, pthread_handle());
  
  INIT_WRAPPER(ptrace, RTLD_NEXT);
  INIT_WRAPPER(pwrite, RTLD_NEXT);
  INIT_WRAPPER(read, RTLD_NEXT);
  INIT_WRAPPER(readahead, RTLD_NEXT);
  INIT_WRAPPER(readlink, RTLD_NEXT);
  INIT_WRAPPER(readlinkat, RTLD_NEXT);
  INIT_WRAPPER(readv, RTLD_NEXT);
  INIT_WRAPPER(realloc, RTLD_NEXT);
  INIT_WRAPPER(reboot, RTLD_NEXT);
  INIT_WRAPPER(recvfrom, RTLD_NEXT);
  INIT_WRAPPER(recvmsg, RTLD_NEXT);
  INIT_WRAPPER(remap_file_pages, RTLD_NEXT);
  INIT_WRAPPER(removexattr, RTLD_NEXT);
  INIT_WRAPPER(rename, RTLD_NEXT);
  INIT_WRAPPER(renameat, RTLD_NEXT);
  INIT_WRAPPER(rmdir, RTLD_NEXT);
  INIT_WRAPPER(sched_getaffinity, RTLD_NEXT);
  INIT_WRAPPER(sched_getparam, RTLD_NEXT);
  INIT_WRAPPER(sched_getscheduler, RTLD_NEXT);
  INIT_WRAPPER(sched_get_priority_max, RTLD_NEXT);
  INIT_WRAPPER(sched_get_priority_min, RTLD_NEXT);
  INIT_WRAPPER(sched_rr_get_interval, RTLD_NEXT);
  INIT_WRAPPER(sched_setaffinity, RTLD_NEXT);
  INIT_WRAPPER(sched_setparam, RTLD_NEXT);
  INIT_WRAPPER(sched_setscheduler, RTLD_NEXT);
  INIT_WRAPPER(sched_yield, RTLD_NEXT);
  INIT_WRAPPER(select, RTLD_NEXT);
  INIT_WRAPPER(semctl, RTLD_NEXT);
  INIT_WRAPPER(semget, RTLD_NEXT);
  INIT_WRAPPER(semop, RTLD_NEXT);
  INIT_WRAPPER(semtimedop, RTLD_NEXT);
  INIT_WRAPPER(sendfile, RTLD_NEXT);
  INIT_WRAPPER(sendmsg, RTLD_NEXT);
  INIT_WRAPPER(sendto, RTLD_NEXT);
  INIT_WRAPPER(setdomainname, RTLD_NEXT);
  INIT_WRAPPER(setfsgid, RTLD_NEXT);
  INIT_WRAPPER(setfsuid, RTLD_NEXT);
  INIT_WRAPPER(setgid, RTLD_NEXT);
  INIT_WRAPPER(setgroups, RTLD_NEXT);
  INIT_WRAPPER(sethostname, RTLD_NEXT);
  INIT_WRAPPER(setitimer, RTLD_NEXT);
  INIT_WRAPPER(setpgid, RTLD_NEXT);
  INIT_WRAPPER(setpriority, RTLD_NEXT);
  INIT_WRAPPER(setregid, RTLD_NEXT);
  INIT_WRAPPER(setresgid, RTLD_NEXT);
  INIT_WRAPPER(setresuid, RTLD_NEXT);
  INIT_WRAPPER(setreuid, RTLD_NEXT);
  INIT_WRAPPER(setrlimit, RTLD_NEXT);
  INIT_WRAPPER(setsid, RTLD_NEXT);
  INIT_WRAPPER(setsockopt, RTLD_NEXT);
  INIT_WRAPPER(settimeofday, RTLD_NEXT);
  INIT_WRAPPER(setuid, RTLD_NEXT);
  INIT_WRAPPER(setxattr, RTLD_NEXT);
  INIT_WRAPPER(shmat, RTLD_NEXT);
  INIT_WRAPPER(shmctl, RTLD_NEXT);
  INIT_WRAPPER(shmget, RTLD_NEXT);
  INIT_WRAPPER(shutdown, RTLD_NEXT);
  INIT_WRAPPER(sigaction, RTLD_NEXT);
  INIT_WRAPPER(sigaltstack, RTLD_NEXT);
  INIT_WRAPPER(sigpending, RTLD_NEXT);
  INIT_WRAPPER(sigprocmask, RTLD_NEXT);
  INIT_WRAPPER(sigreturn, RTLD_NEXT);
  INIT_WRAPPER(sigsuspend, RTLD_NEXT);
  INIT_WRAPPER(sigtimedwait, RTLD_NEXT);
  INIT_WRAPPER(sigwait, RTLD_NEXT);
  INIT_WRAPPER(socket, RTLD_NEXT);
  INIT_WRAPPER(socketpair, RTLD_NEXT);
  INIT_WRAPPER(splice, RTLD_NEXT);
  INIT_WRAPPER(stat, RTLD_NEXT);
  INIT_WRAPPER(statfs, RTLD_NEXT);
  INIT_WRAPPER(swapoff, RTLD_NEXT);
  INIT_WRAPPER(swapon, RTLD_NEXT);
  INIT_WRAPPER(symlink, RTLD_NEXT);
  INIT_WRAPPER(symlinkat, RTLD_NEXT);
  INIT_WRAPPER(sync, RTLD_NEXT);
  INIT_WRAPPER(sync_file_range, RTLD_NEXT);
  INIT_WRAPPER(sysctl, RTLD_NEXT);
  INIT_WRAPPER(sysinfo, RTLD_NEXT);
  INIT_WRAPPER(vsyslog, RTLD_NEXT);
  INIT_WRAPPER(tee, RTLD_NEXT);
  INIT_WRAPPER(time, RTLD_NEXT);
  INIT_WRAPPER(timer_create, RTLD_NEXT);
  INIT_WRAPPER(timer_delete, RTLD_NEXT);
  INIT_WRAPPER(timer_getoverrun, RTLD_NEXT);
  INIT_WRAPPER(timer_gettime, RTLD_NEXT);
  INIT_WRAPPER(timer_settime, RTLD_NEXT);
  INIT_WRAPPER(times, RTLD_NEXT);
  INIT_WRAPPER(truncate, RTLD_NEXT);
  INIT_WRAPPER(umask, RTLD_NEXT);
  INIT_WRAPPER(umount2, RTLD_NEXT);
  INIT_WRAPPER(uname, RTLD_NEXT);
  INIT_WRAPPER(unlink, RTLD_NEXT);
  INIT_WRAPPER(unlinkat, RTLD_NEXT);
  INIT_WRAPPER(unshare, RTLD_NEXT);
  INIT_WRAPPER(ustat, RTLD_NEXT);
  INIT_WRAPPER(utime, RTLD_NEXT);
  INIT_WRAPPER(utimes, RTLD_NEXT);
  INIT_WRAPPER(vfork, RTLD_NEXT);
  INIT_WRAPPER(vhangup, RTLD_NEXT);
  INIT_WRAPPER(vmsplice, RTLD_NEXT);
  INIT_WRAPPER(wait4, RTLD_NEXT);
  INIT_WRAPPER(waitid, RTLD_NEXT);
  INIT_WRAPPER(write, RTLD_NEXT);
  INIT_WRAPPER(writev, RTLD_NEXT);
	}
};

#endif
